GET http://localhost:5000/dienda

###
GET http://localhost:5000/api/characters

###
POST http://localhost:5000/api/characters
Content-Type: application/json

{
    "name": "Helicopter helicopter",
    "quote": "I like trains"
}

###
GET http://localhost:5000/api/characters/3

###
PATCH http://localhost:5000/api/characters/3
Content-Type: application/json

{
    "name": "tomato"
}

### 
PUT http://localhost:5000/api/characters/3
Content-Type: application/json

{
    "name": "Tow Mater"
}

###
DELETE http://localhost:5000/api/characters/9

###
GET http://localhost:5000/1